### ISSUE TITLE
API Suggestion

### ISSUE THREAD

**Issue by jakewtaylor** [lechab/newstatpress#1]
It would be great if you could add a couple of variables to the API, such as

`%lastmonthtotalvisits%` - Last months total visitors

`%lastmonthtotalpageviews%` - Last months total pageviews

This would be really helpful, thanks!

**Comment by lechab** [comment]
It's added in the TODO list :)
It will be present in next version, stay tuned.

**Comment by jakewtaylor** [comment]
Thanks!
