### ISSUE TITLE
IP2nation failed to instal

### ISSUE THREAD

**Issue by Letiteuf55** [lechab/newstatpress#4]
Hello,
when i try to instal IP2nation i got a
```
504 Gateway Time-out
The server didn't respond in time.
```

Is it anything to do to solve this issue ?
Thanks

**Comment by ice00** [comment]
hi,

add those line after the comment section in the beginning of newstatpress.php

```
************************************************************/
           
error_reporting(E_ALL);
ini_set('display_errors', 1);
```
then try to install the ip2nation.
If there are some PHP errors they will pop up into the page (remove those lines after you make the test).

However the problem should be the process killed by your service provider as it takes too much DB/server time to achieve all the process and this did not have a simple solution.

Let me know how the test is doing.
Thanks

**Comment by Letiteuf55** [comment]
in fact it's ok, i just got a timeout but it's installed
