### ISSUE TITLE
How Can I use newstatpress api with php?

### ISSUE THREAD

**Issue by oguzdelioglu** [lechab/newstatpress#6]
http://haircoloridea.top/wp-content/plugins/newstatpress/includes/api/external.php
I want to transfer the data on my sites to a single panel.
I want to read the data from the site you see above with the post method.
Can you give me a sample template?

my codes

```
<?php
$curl = curl_init();
curl_setopt_array($curl, array(
  CURLOPT_URL => "http://haircoloridea.top/wp-content/plugins/newstatpress/includes/api/external.php",
  CURLOPT_RETURNTRANSFER => true,
  CURLOPT_ENCODING => "",
  CURLOPT_MAXREDIRS => 10,
  CURLOPT_TIMEOUT => 30,
  CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
  CURLOPT_CUSTOMREQUEST => "POST",
  CURLOPT_POSTFIELDS => "------WebKitFormBoundary7MA4YWxkTrZu0gW\r\nContent-Disposition: form-data; name=\"VAR\"\r\n\r\ndashboar\r\n------WebKitFormBoundary7MA4YWxkTrZu0gW\r\nContent-Disposition: form-data; name=\"TYP\"\r\n\r\nJSON\r\n------WebKitFormBoundary7MA4YWxkTrZu0gW\r\nContent-Disposition: form-data; name=\"KEY\"\r\n\r\noAQzNPVIKGQ2hAm4uKBCBhePUTMqB0xmlkMJyCqHVmNVVoBqGKeLdLs8vd6uao5HHvHIp9PHDT8EvfQeL22zHUqPLY8GzMInp9qm9uvoSxxUCg4uWbgNpzebdGSJarY7\r\n------WebKitFormBoundary7MA4YWxkTrZu0gW--",
  CURLOPT_HTTPHEADER => array(
    "Accept: */*",
    "Cache-Control: no-cache",
    "Connection: keep-alive",
    "Content-Type: application/x-www-form-urlencoded",
    "Host: haircoloridea.top",
    "Postman-Token: 36bf5618-1344-4d69-b01c-98ce78f66513,02a948b6-584e-4054-a230-89a126ce6582",
    "User-Agent: PostmanRuntime/7.13.0",
    "accept-encoding: gzip, deflate",
    "cache-control: no-cache",
    "content-length: 502",
    "content-type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW",
    "cookie: __cfduid=d1a34cebe2e22bee0aa223b6189acfc941558479451"
  ),
));

$response = curl_exec($curl);
$err = curl_error($curl);

curl_close($curl);

if ($err) {
  echo "cURL Error #:" . $err;
} else {
  echo $response;
}
```

This method does not work.
Thanks.

**Comment by ice00** [comment]
hi,

this is the function I use in multi-newstatpress to call the API:


/**
 * Call the API plugin
 *
 * @param var the variable for API call 
 * @param key the api key
 * @param par the api paramenters
 * @param typ the type of result
 * @return the call result
 */
function nsp_CallApi($site, $var, $key, $par, $typ) {
  $url=$site."/wp-admin/admin-ajax.php";
  $fields = array(
    'action' => 'nsp_external', 
    'VAR' => urlencode($var),
    'KEY' => urlencode($key),
    'PAR' => urlencode($par),
    'TYP' => urlencode($typ),
  );
  $fields_string=http_build_query($fields);
  $curl = curl_init();
  curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);
  curl_setopt($curl, CURLOPT_FOLLOWLOCATION, TRUE);
  curl_setopt($curl, CURLOPT_URL, $url);
  curl_setopt($curl, CURLOPT_POST, 1);
  curl_setopt($curl, CURLOPT_POSTFIELDS, $fields_string);
  $res = curl_exec($curl);
  curl_close($curl);
  if ($typ == "JSON") return json_decode($res, TRUE);
  elseif ($typ == "HTML") return $res;
  else return "";
}

**Comment by oguzdelioglu** [comment]
> hi,
> 
> this is the function I use in multi-newstatpress to call the API:
> 
> /**
> 
> * Call the API plugin
> * @param var the variable for API call
> * @param key the api key
> * @param par the api paramenters
> * @param typ the type of result
> * @return the call result
>   */
>   function nsp_CallApi($site, $var, $key, $par, $typ) {
>   $url=$site."/wp-admin/admin-ajax.php";
>   $fields = array(
>   'action' => 'nsp_external',
>   'VAR' => urlencode($var),
>   'KEY' => urlencode($key),
>   'PAR' => urlencode($par),
>   'TYP' => urlencode($typ),
>   );
>   $fields_string=http_build_query($fields);
>   $curl = curl_init();
>   curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);
>   curl_setopt($curl, CURLOPT_FOLLOWLOCATION, TRUE);
>   curl_setopt($curl, CURLOPT_URL, $url);
>   curl_setopt($curl, CURLOPT_POST, 1);
>   curl_setopt($curl, CURLOPT_POSTFIELDS, $fields_string);
>   $res = curl_exec($curl);
>   curl_close($curl);
>   if ($typ == "JSON") return json_decode($res, TRUE);
>   elseif ($typ == "HTML") return $res;
>   else return "";
>   }

nsp_CallApi("http://chickenrecipeseasy.top","dashboard","BXugyNIgtwlXtNKPTSC3ONynWNrYMCKelxCWCsg3z6XmugzuvBEXFDUOPXWOYZNc7TW1KCQyQNuVQoh7lYOqYxXNLOY7Cv8aImtM94WaF9jXV8h8ErTKOdA3nfieh5kS","","HTML");

Error given: Not authorized API access

**Comment by ice00** [comment]
Hi,

remember that key you pass into the API is not static, but change according with the moment it is called:

echo "<script type=\"text/javascript\">
           $.post(\"$url\", {
             URL: \"$url2\",
             VAR: \"dashboard\",
             KEY: \"".md5(gmdate('m-d-y H i').$site['key'])."\",
             PAR: \"\",
             TYP: \"HTML\"
           }, 
           function(data,status){
           console.log(status);
             $( \"#loader-$priority\").hide();
             $( \"#result-$priority\" ).html( data );
           }, \"html\");
         </script>";

**Comment by oguzdelioglu** [comment]
401 Authorization Required

> Hi,
> 
> remember that key you pass into the API is not static, but change according with the moment it is called:
> 
> echo "<script type="text/javascript">
> $.post("$url", {
> URL: "$url2",
> VAR: "dashboard",
> KEY: "".md5(gmdate('m-d-y H i').$site['key'])."",
> PAR: "",
> TYP: "HTML"
> },
> function(data,status){
> console.log(status);
> $( "#loader-$priority").hide();
> $( "#result-$priority" ).html( data );
> }, "html");
> </script>";

401 Authorization Required

I cannot get data from the site on the different server.
I was able to read the data of sites on the same server.

**Comment by ice00** [comment]
hi,

if you use this way from PHP:
`$result=nsp_CallApi($site['site'], 'overview', md5(gmdate('m-d-y H i').$site["key"]), 'dashboard');`

with the new rules about cross site call to prevent fraudolent use of server resources implemented by all browser/server, then yes, you can be blocked by the server you call. 
You probably need to open the access to the server (by adding a rule to Apache with your service provider) or allow cross site call by custom HTML header into the server to open.

I did not use that way as I find that javascript version call with post are (actually) not subject to that restriction:

```
$url="http://your_server_path_to/wrapper.php";

echo "<script type="text/javascript">
$.post("$url", {
URL: "$url2",
VAR: "dashboard",
KEY: "".md5(gmdate('m-d-y H i').$site['key'])."",
PAR: "",
TYP: "HTML"
},
function(data,status){
console.log(status);
$( "#loader-$priority").hide();
$( "#result-$priority" ).html( data );
}, "html");
</script>";
```


and wrapper.php are:

```
<?php
include_once "the file with nsp_callAPi definition";

$site = $_POST['URL'];
$var = $_POST['VAR'];
$key = $_POST['KEY'];
$par = $_POST['PAR'];
$typ = $_POST['TYP'];
echo nsp_CallApi($site, $var, $key, $par, $typ);
?>
```
