### ISSUE TITLE
Not sending daily stat emails

### ISSUE THREAD

**Issue by KGIII** [lechab/newstatpress#7]
When I push the test button, it says there was an error.

It also says that the cron job must be enabled. Presumably that's a WP cron job and not something I have to add manually?

It stopped sending after the most recent update a few days ago. It worked fine before that. I've added no new plugins or anything, as the site is feature-complete. It ran well for like 10 months.

**Comment by ice00** [comment]
Worpress had required that the plugin is refactored to be more robust and so it must be "error" free by erasing all PHP-Wordpress-style scanning (potential) errors.

So many fields are sanitized early and this could had cause problem in mail sending (cron job is provided by worpress, so it is not the case).

You can use version 1.3.6 until it will be fixed

**Comment by KGIII** [comment]
Thanks for the speedy reply. I can always check manually and then keep an eye on it in case I notice anything else amiss. It'll get fixed when it gets fixed. It's not a major change in my workflow or anything like that and this way I may notice any other bugs.

**Comment by ice00** [comment]
Another issue is on stats variables on widget. I cannot let more to have HTML commands inside the text, so I will had to provide a %br% commands instead to generate a line break to compensate it.

**Comment by KGIII** [comment]
I hadn't noticed that one. I don't bother with the widget. If I get a minute, I'll go through all the other settings looking for bugs.

I'm used to it. I'm on the Lubuntu (Linux, an official Ubuntu flavor) dev team. Spotting bugs is what I do.

**Comment by ice00** [comment]
If you can test the current git version, it could be resolved

**Comment by KGIII** [comment]
I am so sorry. I got no email notification of your reply. I only noticed the reply when I checked manually. I'll check GItHub's notification settings.

I'm not actually sure how to go about doing all that.

**Comment by KGIII** [comment]
You can mark this resolved, at least from my perspective. Loading the overview page was also reasonably responsive.
